### ISSUE TITLE
#L13 Hyperlink Issue | #L13超链接错误

### ISSUE THREAD

**Issue by MapMaths** [sea-horizon/sea-horizon.github.io#1]
https://github.com/sea-horion/sea-horion.github.io/blob/899bed8dbe8bb689d33c0b6ec60b1167efd14981/index.html#L13

Hyperlink code `<a href="http://github.com/MapMaths/" target="_blank">GitHub|</a>` is wrong and should be change to `<a href="http://github.com/sea-horion/" target="_blank">GitHub|</a>`

————————————————————————————————————————————

超链接程序`<a href="http://github.com/MapMaths/" target="_blank">GitHub|</a>`有错，且应被改为`<a href="http://github.com/sea-horion/" target="_blank">GitHub|</a>`

**Comment by sea-horizon** [comment]
ok

**Comment by MapMaths** [comment]
See, thanks!
